# Generated by Django 4.2.4 on 2023-08-23 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physical_storage', '0003_alter_dimensionprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhyscialStorageForm',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_item', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(max_length=20)),
                ('description_of_item', models.TextField()),
                ('value_of_item_in_naira', models.CharField(max_length=30)),
                ('storage_duration_in_month', models.PositiveIntegerField(max_length=5)),
                ('choose_a_storage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_storage.physicalstorage')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
