# Generated by Django 4.2.4 on 2023-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0004_physcialstorageform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physcialstorageform',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='physcialstorageform',
            name='storage_duration_in_month',
            field=models.PositiveIntegerField(),
        ),
    ]
