# Generated by Django 4.2.4 on 2023-08-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0005_alter_physcialstorageform_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physcialstorageform',
            name='customer',
        ),
        migrations.AddField(
            model_name='physcialstorageform',
            name='dimension_of_storage',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='physical_storage.dimensionprice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physcialstorageform',
            name='choose_a_storage_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='physical_storage.physicalstorage'),
        ),
    ]
