# Generated by Django 4.2.4 on 2023-09-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0007_remove_physcialstorageform_dimension_of_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physcialstorageform',
            name='choose_a_storage_type',
        ),
        migrations.RemoveField(
            model_name='physcialstorageform',
            name='quantity',
        ),
        migrations.AddField(
            model_name='physcialstorageform',
            name='image',
            field=models.ImageField(default=1, upload_to='item_image/'),
            preserve_default=False,
        ),
    ]
