# Generated by Django 4.2.4 on 2023-09-04 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physical_storage', '0008_remove_physcialstorageform_choose_a_storage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physcialstorageform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
