# Generated by Django 4.2.4 on 2023-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0009_physcialstorageform_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physcialstorageform',
            old_name='user',
            new_name='userid',
        ),
    ]
