# Generated by Django 4.2.4 on 2023-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0010_rename_user_physcialstorageform_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physcialstorageform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_image/'),
        ),
    ]
