# Generated by Django 4.2.4 on 2023-09-06 12:48

from django.db import migrations, models
import physical_storage.customer_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0011_alter_physcialstorageform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='physcialstorageform',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='physcialstorageform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=physical_storage.customer_form.models.user_upload_path),
        ),
    ]
