# Generated by Django 4.2.4 on 2023-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0012_physcialstorageform_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physcialstorageform',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='storage_forms', to='physical_storage.physcialstorageform'),
        ),
        migrations.AlterField(
            model_name='physcialstorageform',
            name='name_of_item',
            field=models.TextField(),
        ),
    ]
