# Generated by Django 4.2.4 on 2023-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0013_physcialstorageform_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physcialstorageform',
            name='items',
            field=models.ManyToManyField(blank=True, default=list, to='physical_storage.physcialstorageform'),
        ),
    ]
