# Generated by Django 4.2.4 on 2023-09-13 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_storage', '0015_remove_physcialstorageform_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='physcialstorageform',
            name='list_of_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
